/*flexberryautogenerated="true"*/
namespace IIS.Актуализация_Задач
{
    using System;
    using ICSSoft.STORMNET.Web.Controls;

    using Resources;

    public partial class ИтерацияL : BaseListForm<Итерация>
    {
        /// <summary>
        /// Конструктор без параметров,
        /// инициализирует свойства, соответствующие конкретной форме.
        /// </summary>
        public ИтерацияL() : base(Итерация.Views.ИтерацияL)
        {
            EditPage = ИтерацияE.FormPath;
        }
                
        /// <summary>
        /// Путь до формы.
        /// </summary>
        public static string FormPath
        {
            get { return "~/forms/Iteraciya/IteraciyaL.aspx"; }
        }

        /// <summary>
        /// Вызывается самым первым в Page_Load.
        /// </summary>
        protected override void Preload()
        {
        }

        /// <summary>
        /// Вызывается самым последним в Page_Load.
        /// </summary>
        protected override void Postload()
        {
        }
    }
}
