//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Актуализация_Задач
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Задача.
    /// </summary>
    // *** Start programmer edit section *** (Задача CustomAttributes)

    // *** End programmer edit section *** (Задача CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЗадачаE", new string[] {
            "НазваниеТемыНаФоруме as \'Название темы на форуме\'",
            "СсылкаНаТему as \'Ссылка на тему\'",
            "НомерЗадачиВTfs as \'Номер задачи в tfs\'",
            "СсылкаНаЗадачуВTfs as \'Ссылка на задачу в tfs\'",
            "Проект",
            "Исполнитель",
            "Исполнитель.ФИО as \'ФИО\'",
            "Комментарий as \'Комментарий\'",
            "ВыполнитьК as \'Выполнить К\'",
            "Поддержка",
            "Статус as \'Статус\'",
            "Приоритет as \'Приоритет\'",
            "ВИтерации",
            "Проект.НазваниеПроекта as \'Название проекта\'"}, Hidden=new string[] {
            "Исполнитель.ФИО",
            "Проект.НазваниеПроекта"})]
    [MasterViewDefineAttribute("ЗадачаE", "Проект", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "НазваниеПроекта")]
    [MasterViewDefineAttribute("ЗадачаE", "Исполнитель", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    [View("ЗадачаL", new string[] {
            "НазваниеТемыНаФоруме as \'Название темы на форуме\'",
            "СсылкаНаТему as \'Ссылка на тему\'",
            "НомерЗадачиВTfs as \'Номер задачи в tfs\'",
            "СсылкаНаЗадачуВTfs as \'Ссылка на задачу в tfs\'",
            "Исполнитель.ФИО as \'ФИО\'",
            "Комментарий as \'Комментарий\'",
            "ВыполнитьК as \'Выполнить К\'",
            "Поддержка",
            "Статус as \'Статус\'",
            "Приоритет as \'Приоритет\'",
            "ВИтерации",
            "Проект.НазваниеПроекта as \'Название проекта\'"})]
    [View("ЗадачаПоддержкиL", new string[] {
            "НазваниеТемыНаФоруме as \'Название темы но форуме\'",
            "СсылкаНаТему as \'Ссылка на тему\'",
            "НомерЗадачиВTfs as \'Номер задачи в tfs\'",
            "СсылкаНаЗадачуВTfs as \'Ссылка на задачу в tfs\'",
            "Комментарий",
            "ВыполнитьК as \'Выполнить к\'",
            "Исполнитель.ФИО as \'Исполнитель\'",
            "Приоритет",
            "Статус",
            "Поддержка"})]
    [View("ЗадачаРазвитияL", new string[] {
            "НазваниеТемыНаФоруме as \'Название темы на форуме\'",
            "СсылкаНаТему as \'Ссылка на тему\'",
            "НомерЗадачиВTfs as \'Номер задачи в tfs\'",
            "СсылкаНаЗадачуВTfs as \'Ссылка на задачу в tfs\'",
            "Комментарий",
            "ВыполнитьК as \'Выполнить к \'",
            "Исполнитель.ФИО as \'Исполнитель\'",
            "ВИтерации as \'В итерации\'",
            "Проект.НазваниеПроекта as \'Проект\'",
            "Поддержка"}, Hidden=new string[] {
            "Поддержка"})]
    public class Задача : ICSSoft.STORMNET.DataObject
    {
        
        private string fНазваниеТемыНаФоруме;
        
        private string fСсылкаНаТему;
        
        private int fНомерЗадачиВTfs;
        
        private string fСсылкаНаЗадачуВTfs;
        
        private int fПриоритет;
        
        private string fКомментарий;
        
        private System.DateTime fВыполнитьК;
        
        private IIS.Актуализация_Задач.СтатусЗадачи fСтатус;
        
        private bool fВИтерации;
        
        private bool fПоддержка;
        
        private IIS.Актуализация_Задач.Исполнитель fИсполнитель;
        
        private IIS.Актуализация_Задач.Проект fПроект;
        
        // *** Start programmer edit section *** (Задача CustomMembers)

        // *** End programmer edit section *** (Задача CustomMembers)

        
        /// <summary>
        /// НазваниеТемыНаФоруме.
        /// </summary>
        // *** Start programmer edit section *** (Задача.НазваниеТемыНаФоруме CustomAttributes)

        // *** End programmer edit section *** (Задача.НазваниеТемыНаФоруме CustomAttributes)
        [StrLen(255)]
        public virtual string НазваниеТемыНаФоруме
        {
            get
            {
                // *** Start programmer edit section *** (Задача.НазваниеТемыНаФоруме Get start)

                // *** End programmer edit section *** (Задача.НазваниеТемыНаФоруме Get start)
                string result = this.fНазваниеТемыНаФоруме;
                // *** Start programmer edit section *** (Задача.НазваниеТемыНаФоруме Get end)

                // *** End programmer edit section *** (Задача.НазваниеТемыНаФоруме Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Задача.НазваниеТемыНаФоруме Set start)

                // *** End programmer edit section *** (Задача.НазваниеТемыНаФоруме Set start)
                this.fНазваниеТемыНаФоруме = value;
                // *** Start programmer edit section *** (Задача.НазваниеТемыНаФоруме Set end)

                // *** End programmer edit section *** (Задача.НазваниеТемыНаФоруме Set end)
            }
        }
        
        /// <summary>
        /// СсылкаНаТему.
        /// </summary>
        // *** Start programmer edit section *** (Задача.СсылкаНаТему CustomAttributes)

        // *** End programmer edit section *** (Задача.СсылкаНаТему CustomAttributes)
        [StrLen(255)]
        public virtual string СсылкаНаТему
        {
            get
            {
                // *** Start programmer edit section *** (Задача.СсылкаНаТему Get start)

                // *** End programmer edit section *** (Задача.СсылкаНаТему Get start)
                string result = this.fСсылкаНаТему;
                // *** Start programmer edit section *** (Задача.СсылкаНаТему Get end)

                // *** End programmer edit section *** (Задача.СсылкаНаТему Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Задача.СсылкаНаТему Set start)

                // *** End programmer edit section *** (Задача.СсылкаНаТему Set start)
                this.fСсылкаНаТему = value;
                // *** Start programmer edit section *** (Задача.СсылкаНаТему Set end)

                // *** End programmer edit section *** (Задача.СсылкаНаТему Set end)
            }
        }
        
        /// <summary>
        /// НомерЗадачиВTfs.
        /// </summary>
        // *** Start programmer edit section *** (Задача.НомерЗадачиВTfs CustomAttributes)

        // *** End programmer edit section *** (Задача.НомерЗадачиВTfs CustomAttributes)
        public virtual int НомерЗадачиВTfs
        {
            get
            {
                // *** Start programmer edit section *** (Задача.НомерЗадачиВTfs Get start)

                // *** End programmer edit section *** (Задача.НомерЗадачиВTfs Get start)
                int result = this.fНомерЗадачиВTfs;
                // *** Start programmer edit section *** (Задача.НомерЗадачиВTfs Get end)

                // *** End programmer edit section *** (Задача.НомерЗадачиВTfs Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Задача.НомерЗадачиВTfs Set start)

                // *** End programmer edit section *** (Задача.НомерЗадачиВTfs Set start)
                this.fНомерЗадачиВTfs = value;
                // *** Start programmer edit section *** (Задача.НомерЗадачиВTfs Set end)

                // *** End programmer edit section *** (Задача.НомерЗадачиВTfs Set end)
            }
        }
        
        /// <summary>
        /// СсылкаНаЗадачуВTfs.
        /// </summary>
        // *** Start programmer edit section *** (Задача.СсылкаНаЗадачуВTfs CustomAttributes)

        // *** End programmer edit section *** (Задача.СсылкаНаЗадачуВTfs CustomAttributes)
        [StrLen(255)]
        public virtual string СсылкаНаЗадачуВTfs
        {
            get
            {
                // *** Start programmer edit section *** (Задача.СсылкаНаЗадачуВTfs Get start)

                // *** End programmer edit section *** (Задача.СсылкаНаЗадачуВTfs Get start)
                string result = this.fСсылкаНаЗадачуВTfs;
                // *** Start programmer edit section *** (Задача.СсылкаНаЗадачуВTfs Get end)

                // *** End programmer edit section *** (Задача.СсылкаНаЗадачуВTfs Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Задача.СсылкаНаЗадачуВTfs Set start)

                // *** End programmer edit section *** (Задача.СсылкаНаЗадачуВTfs Set start)
                this.fСсылкаНаЗадачуВTfs = value;
                // *** Start programmer edit section *** (Задача.СсылкаНаЗадачуВTfs Set end)

                // *** End programmer edit section *** (Задача.СсылкаНаЗадачуВTfs Set end)
            }
        }
        
        /// <summary>
        /// Приоритет.
        /// </summary>
        // *** Start programmer edit section *** (Задача.Приоритет CustomAttributes)

        // *** End programmer edit section *** (Задача.Приоритет CustomAttributes)
        public virtual int Приоритет
        {
            get
            {
                // *** Start programmer edit section *** (Задача.Приоритет Get start)

                // *** End programmer edit section *** (Задача.Приоритет Get start)
                int result = this.fПриоритет;
                // *** Start programmer edit section *** (Задача.Приоритет Get end)

                // *** End programmer edit section *** (Задача.Приоритет Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Задача.Приоритет Set start)

                // *** End programmer edit section *** (Задача.Приоритет Set start)
                this.fПриоритет = value;
                // *** Start programmer edit section *** (Задача.Приоритет Set end)

                // *** End programmer edit section *** (Задача.Приоритет Set end)
            }
        }
        
        /// <summary>
        /// Комментарий.
        /// </summary>
        // *** Start programmer edit section *** (Задача.Комментарий CustomAttributes)

        // *** End programmer edit section *** (Задача.Комментарий CustomAttributes)
        [StrLen(255)]
        public virtual string Комментарий
        {
            get
            {
                // *** Start programmer edit section *** (Задача.Комментарий Get start)

                // *** End programmer edit section *** (Задача.Комментарий Get start)
                string result = this.fКомментарий;
                // *** Start programmer edit section *** (Задача.Комментарий Get end)

                // *** End programmer edit section *** (Задача.Комментарий Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Задача.Комментарий Set start)

                // *** End programmer edit section *** (Задача.Комментарий Set start)
                this.fКомментарий = value;
                // *** Start programmer edit section *** (Задача.Комментарий Set end)

                // *** End programmer edit section *** (Задача.Комментарий Set end)
            }
        }
        
        /// <summary>
        /// ВыполнитьК.
        /// </summary>
        // *** Start programmer edit section *** (Задача.ВыполнитьК CustomAttributes)

        // *** End programmer edit section *** (Задача.ВыполнитьК CustomAttributes)
        public virtual System.DateTime ВыполнитьК
        {
            get
            {
                // *** Start programmer edit section *** (Задача.ВыполнитьК Get start)

                // *** End programmer edit section *** (Задача.ВыполнитьК Get start)
                System.DateTime result = this.fВыполнитьК;
                // *** Start programmer edit section *** (Задача.ВыполнитьК Get end)

                // *** End programmer edit section *** (Задача.ВыполнитьК Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Задача.ВыполнитьК Set start)

                // *** End programmer edit section *** (Задача.ВыполнитьК Set start)
                this.fВыполнитьК = value;
                // *** Start programmer edit section *** (Задача.ВыполнитьК Set end)

                // *** End programmer edit section *** (Задача.ВыполнитьК Set end)
            }
        }
        
        /// <summary>
        /// Статус.
        /// </summary>
        // *** Start programmer edit section *** (Задача.Статус CustomAttributes)

        // *** End programmer edit section *** (Задача.Статус CustomAttributes)
        public virtual IIS.Актуализация_Задач.СтатусЗадачи Статус
        {
            get
            {
                // *** Start programmer edit section *** (Задача.Статус Get start)

                // *** End programmer edit section *** (Задача.Статус Get start)
                IIS.Актуализация_Задач.СтатусЗадачи result = this.fСтатус;
                // *** Start programmer edit section *** (Задача.Статус Get end)

                // *** End programmer edit section *** (Задача.Статус Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Задача.Статус Set start)

                // *** End programmer edit section *** (Задача.Статус Set start)
                this.fСтатус = value;
                // *** Start programmer edit section *** (Задача.Статус Set end)

                // *** End programmer edit section *** (Задача.Статус Set end)
            }
        }
        
        /// <summary>
        /// ВИтерации.
        /// </summary>
        // *** Start programmer edit section *** (Задача.ВИтерации CustomAttributes)

        // *** End programmer edit section *** (Задача.ВИтерации CustomAttributes)
        public virtual bool ВИтерации
        {
            get
            {
                // *** Start programmer edit section *** (Задача.ВИтерации Get start)

                // *** End programmer edit section *** (Задача.ВИтерации Get start)
                bool result = this.fВИтерации;
                // *** Start programmer edit section *** (Задача.ВИтерации Get end)

                // *** End programmer edit section *** (Задача.ВИтерации Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Задача.ВИтерации Set start)

                // *** End programmer edit section *** (Задача.ВИтерации Set start)
                this.fВИтерации = value;
                // *** Start programmer edit section *** (Задача.ВИтерации Set end)

                // *** End programmer edit section *** (Задача.ВИтерации Set end)
            }
        }
        
        /// <summary>
        /// Поддержка.
        /// </summary>
        // *** Start programmer edit section *** (Задача.Поддержка CustomAttributes)

        // *** End programmer edit section *** (Задача.Поддержка CustomAttributes)
        public virtual bool Поддержка
        {
            get
            {
                // *** Start programmer edit section *** (Задача.Поддержка Get start)

                // *** End programmer edit section *** (Задача.Поддержка Get start)
                bool result = this.fПоддержка;
                // *** Start programmer edit section *** (Задача.Поддержка Get end)

                // *** End programmer edit section *** (Задача.Поддержка Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Задача.Поддержка Set start)

                // *** End programmer edit section *** (Задача.Поддержка Set start)
                this.fПоддержка = value;
                // *** Start programmer edit section *** (Задача.Поддержка Set end)

                // *** End programmer edit section *** (Задача.Поддержка Set end)
            }
        }
        
        /// <summary>
        /// Задача.
        /// </summary>
        // *** Start programmer edit section *** (Задача.Исполнитель CustomAttributes)

        // *** End programmer edit section *** (Задача.Исполнитель CustomAttributes)
        [PropertyStorage(new string[] {
                "Исполнитель"})]
        [NotNull()]
        public virtual IIS.Актуализация_Задач.Исполнитель Исполнитель
        {
            get
            {
                // *** Start programmer edit section *** (Задача.Исполнитель Get start)

                // *** End programmer edit section *** (Задача.Исполнитель Get start)
                IIS.Актуализация_Задач.Исполнитель result = this.fИсполнитель;
                // *** Start programmer edit section *** (Задача.Исполнитель Get end)

                // *** End programmer edit section *** (Задача.Исполнитель Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Задача.Исполнитель Set start)

                // *** End programmer edit section *** (Задача.Исполнитель Set start)
                this.fИсполнитель = value;
                // *** Start programmer edit section *** (Задача.Исполнитель Set end)

                // *** End programmer edit section *** (Задача.Исполнитель Set end)
            }
        }
        
        /// <summary>
        /// Задача.
        /// </summary>
        // *** Start programmer edit section *** (Задача.Проект CustomAttributes)

        // *** End programmer edit section *** (Задача.Проект CustomAttributes)
        [PropertyStorage(new string[] {
                "Проект"})]
        public virtual IIS.Актуализация_Задач.Проект Проект
        {
            get
            {
                // *** Start programmer edit section *** (Задача.Проект Get start)

                // *** End programmer edit section *** (Задача.Проект Get start)
                IIS.Актуализация_Задач.Проект result = this.fПроект;
                // *** Start programmer edit section *** (Задача.Проект Get end)

                // *** End programmer edit section *** (Задача.Проект Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Задача.Проект Set start)

                // *** End programmer edit section *** (Задача.Проект Set start)
                this.fПроект = value;
                // *** Start programmer edit section *** (Задача.Проект Set end)

                // *** End programmer edit section *** (Задача.Проект Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЗадачаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗадачаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗадачаE", typeof(IIS.Актуализация_Задач.Задача));
                }
            }
            
            /// <summary>
            /// "ЗадачаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗадачаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗадачаL", typeof(IIS.Актуализация_Задач.Задача));
                }
            }
            
            /// <summary>
            /// "ЗадачаПоддержкиL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗадачаПоддержкиL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗадачаПоддержкиL", typeof(IIS.Актуализация_Задач.Задача));
                }
            }
            
            /// <summary>
            /// "ЗадачаРазвитияL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗадачаРазвитияL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗадачаРазвитияL", typeof(IIS.Актуализация_Задач.Задача));
                }
            }
        }
    }
}
