//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Актуализация_Задач
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Исполнитель.
    /// </summary>
    // *** Start programmer edit section *** (Исполнитель CustomAttributes)

    // *** End programmer edit section *** (Исполнитель CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ИсполнительE", new string[] {
            "ФИО as \'ФИО\'"})]
    [View("ИсполнительL", new string[] {
            "ФИО as \'ФИО\'"})]
    public class Исполнитель : ICSSoft.STORMNET.DataObject
    {
        
        private string fФИО;
        
        // *** Start programmer edit section *** (Исполнитель CustomMembers)

        // *** End programmer edit section *** (Исполнитель CustomMembers)

        
        /// <summary>
        /// ФИО.
        /// </summary>
        // *** Start programmer edit section *** (Исполнитель.ФИО CustomAttributes)

        // *** End programmer edit section *** (Исполнитель.ФИО CustomAttributes)
        [StrLen(255)]
        public virtual string ФИО
        {
            get
            {
                // *** Start programmer edit section *** (Исполнитель.ФИО Get start)

                // *** End programmer edit section *** (Исполнитель.ФИО Get start)
                string result = this.fФИО;
                // *** Start programmer edit section *** (Исполнитель.ФИО Get end)

                // *** End programmer edit section *** (Исполнитель.ФИО Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Исполнитель.ФИО Set start)

                // *** End programmer edit section *** (Исполнитель.ФИО Set start)
                this.fФИО = value;
                // *** Start programmer edit section *** (Исполнитель.ФИО Set end)

                // *** End programmer edit section *** (Исполнитель.ФИО Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ИсполнительE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ИсполнительE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ИсполнительE", typeof(IIS.Актуализация_Задач.Исполнитель));
                }
            }
            
            /// <summary>
            /// "ИсполнительL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ИсполнительL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ИсполнительL", typeof(IIS.Актуализация_Задач.Исполнитель));
                }
            }
        }
    }
}
