//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Актуализация_Задач
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Итерация.
    /// </summary>
    // *** Start programmer edit section *** (Итерация CustomAttributes)

    // *** End programmer edit section *** (Итерация CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ИтерацияE", new string[] {
            "ЧислоСозданныхТемНаФоруме as \'Число созданных тем на форуме\'",
            "ЧислоСозданныхЗадач as \'Число созданных задач\'",
            "ЧислоТемБезИсправлений as \'Число тем без исправлений\'",
            "ДатаНачала",
            "ДатаОкончания",
            "Дежурный.ФИО",
            "Дежурный"}, Hidden=new string[] {
            "Дежурный.ФИО"})]
    [MasterViewDefineAttribute("ИтерацияE", "Дежурный", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    [View("ИтерацияL", new string[] {
            "ЧислоСозданныхТемНаФоруме as \'Число созданных тем на форуме\'",
            "ЧислоСозданныхЗадач as \'Число созданных задач\'",
            "ЧислоТемБезИсправлений as \'Число тем без исправлений\'",
            "ДатаНачала",
            "ДатаОкончания",
            "Дежурный.ФИО",
            "Дежурный"}, Hidden=new string[] {
            "Дежурный.ФИО"})]
    [MasterViewDefineAttribute("ИтерацияL", "Дежурный", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "")]
    public class Итерация : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДатаНачала;
        
        private System.DateTime fДатаОкончания;
        
        private int fЧислоСозданныхТемНаФоруме;
        
        private int fЧислоСозданныхЗадач;
        
        private int fЧислоТемБезИсправлений;
        
        private IIS.Актуализация_Задач.Исполнитель fДежурный;
        
        // *** Start programmer edit section *** (Итерация CustomMembers)

        // *** End programmer edit section *** (Итерация CustomMembers)

        
        /// <summary>
        /// ДатаНачала.
        /// </summary>
        // *** Start programmer edit section *** (Итерация.ДатаНачала CustomAttributes)

        // *** End programmer edit section *** (Итерация.ДатаНачала CustomAttributes)
        public virtual System.DateTime ДатаНачала
        {
            get
            {
                // *** Start programmer edit section *** (Итерация.ДатаНачала Get start)

                // *** End programmer edit section *** (Итерация.ДатаНачала Get start)
                System.DateTime result = this.fДатаНачала;
                // *** Start programmer edit section *** (Итерация.ДатаНачала Get end)

                // *** End programmer edit section *** (Итерация.ДатаНачала Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Итерация.ДатаНачала Set start)

                // *** End programmer edit section *** (Итерация.ДатаНачала Set start)
                this.fДатаНачала = value;
                // *** Start programmer edit section *** (Итерация.ДатаНачала Set end)

                // *** End programmer edit section *** (Итерация.ДатаНачала Set end)
            }
        }
        
        /// <summary>
        /// ДатаОкончания.
        /// </summary>
        // *** Start programmer edit section *** (Итерация.ДатаОкончания CustomAttributes)

        // *** End programmer edit section *** (Итерация.ДатаОкончания CustomAttributes)
        public virtual System.DateTime ДатаОкончания
        {
            get
            {
                // *** Start programmer edit section *** (Итерация.ДатаОкончания Get start)

                // *** End programmer edit section *** (Итерация.ДатаОкончания Get start)
                System.DateTime result = this.fДатаОкончания;
                // *** Start programmer edit section *** (Итерация.ДатаОкончания Get end)

                // *** End programmer edit section *** (Итерация.ДатаОкончания Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Итерация.ДатаОкончания Set start)

                // *** End programmer edit section *** (Итерация.ДатаОкончания Set start)
                this.fДатаОкончания = value;
                // *** Start programmer edit section *** (Итерация.ДатаОкончания Set end)

                // *** End programmer edit section *** (Итерация.ДатаОкончания Set end)
            }
        }
        
        /// <summary>
        /// ЧислоСозданныхТемНаФоруме.
        /// </summary>
        // *** Start programmer edit section *** (Итерация.ЧислоСозданныхТемНаФоруме CustomAttributes)

        // *** End programmer edit section *** (Итерация.ЧислоСозданныхТемНаФоруме CustomAttributes)
        public virtual int ЧислоСозданныхТемНаФоруме
        {
            get
            {
                // *** Start programmer edit section *** (Итерация.ЧислоСозданныхТемНаФоруме Get start)

                // *** End programmer edit section *** (Итерация.ЧислоСозданныхТемНаФоруме Get start)
                int result = this.fЧислоСозданныхТемНаФоруме;
                // *** Start programmer edit section *** (Итерация.ЧислоСозданныхТемНаФоруме Get end)

                // *** End programmer edit section *** (Итерация.ЧислоСозданныхТемНаФоруме Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Итерация.ЧислоСозданныхТемНаФоруме Set start)

                // *** End programmer edit section *** (Итерация.ЧислоСозданныхТемНаФоруме Set start)
                this.fЧислоСозданныхТемНаФоруме = value;
                // *** Start programmer edit section *** (Итерация.ЧислоСозданныхТемНаФоруме Set end)

                // *** End programmer edit section *** (Итерация.ЧислоСозданныхТемНаФоруме Set end)
            }
        }
        
        /// <summary>
        /// ЧислоСозданныхЗадач.
        /// </summary>
        // *** Start programmer edit section *** (Итерация.ЧислоСозданныхЗадач CustomAttributes)

        // *** End programmer edit section *** (Итерация.ЧислоСозданныхЗадач CustomAttributes)
        public virtual int ЧислоСозданныхЗадач
        {
            get
            {
                // *** Start programmer edit section *** (Итерация.ЧислоСозданныхЗадач Get start)

                // *** End programmer edit section *** (Итерация.ЧислоСозданныхЗадач Get start)
                int result = this.fЧислоСозданныхЗадач;
                // *** Start programmer edit section *** (Итерация.ЧислоСозданныхЗадач Get end)

                // *** End programmer edit section *** (Итерация.ЧислоСозданныхЗадач Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Итерация.ЧислоСозданныхЗадач Set start)

                // *** End programmer edit section *** (Итерация.ЧислоСозданныхЗадач Set start)
                this.fЧислоСозданныхЗадач = value;
                // *** Start programmer edit section *** (Итерация.ЧислоСозданныхЗадач Set end)

                // *** End programmer edit section *** (Итерация.ЧислоСозданныхЗадач Set end)
            }
        }
        
        /// <summary>
        /// ЧислоТемБезИсправлений.
        /// </summary>
        // *** Start programmer edit section *** (Итерация.ЧислоТемБезИсправлений CustomAttributes)

        // *** End programmer edit section *** (Итерация.ЧислоТемБезИсправлений CustomAttributes)
        public virtual int ЧислоТемБезИсправлений
        {
            get
            {
                // *** Start programmer edit section *** (Итерация.ЧислоТемБезИсправлений Get start)

                // *** End programmer edit section *** (Итерация.ЧислоТемБезИсправлений Get start)
                int result = this.fЧислоТемБезИсправлений;
                // *** Start programmer edit section *** (Итерация.ЧислоТемБезИсправлений Get end)

                // *** End programmer edit section *** (Итерация.ЧислоТемБезИсправлений Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Итерация.ЧислоТемБезИсправлений Set start)

                // *** End programmer edit section *** (Итерация.ЧислоТемБезИсправлений Set start)
                this.fЧислоТемБезИсправлений = value;
                // *** Start programmer edit section *** (Итерация.ЧислоТемБезИсправлений Set end)

                // *** End programmer edit section *** (Итерация.ЧислоТемБезИсправлений Set end)
            }
        }
        
        /// <summary>
        /// Итерация.
        /// </summary>
        // *** Start programmer edit section *** (Итерация.Дежурный CustomAttributes)

        // *** End programmer edit section *** (Итерация.Дежурный CustomAttributes)
        [PropertyStorage(new string[] {
                "Дежурный"})]
        [NotNull()]
        public virtual IIS.Актуализация_Задач.Исполнитель Дежурный
        {
            get
            {
                // *** Start programmer edit section *** (Итерация.Дежурный Get start)

                // *** End programmer edit section *** (Итерация.Дежурный Get start)
                IIS.Актуализация_Задач.Исполнитель result = this.fДежурный;
                // *** Start programmer edit section *** (Итерация.Дежурный Get end)

                // *** End programmer edit section *** (Итерация.Дежурный Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Итерация.Дежурный Set start)

                // *** End programmer edit section *** (Итерация.Дежурный Set start)
                this.fДежурный = value;
                // *** Start programmer edit section *** (Итерация.Дежурный Set end)

                // *** End programmer edit section *** (Итерация.Дежурный Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ИтерацияE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ИтерацияE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ИтерацияE", typeof(IIS.Актуализация_Задач.Итерация));
                }
            }
            
            /// <summary>
            /// "ИтерацияL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ИтерацияL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ИтерацияL", typeof(IIS.Актуализация_Задач.Итерация));
                }
            }
        }
    }
}
