//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Актуализация_Задач
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Проект.
    /// </summary>
    // *** Start programmer edit section *** (Проект CustomAttributes)

    // *** End programmer edit section *** (Проект CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПроектE", new string[] {
            "НазваниеПроекта as \'Название проекта\'"})]
    [View("ПроектL", new string[] {
            "НазваниеПроекта as \'Название проекта\'"})]
    public class Проект : ICSSoft.STORMNET.DataObject
    {
        
        private string fНазваниеПроекта;
        
        // *** Start programmer edit section *** (Проект CustomMembers)

        // *** End programmer edit section *** (Проект CustomMembers)

        
        /// <summary>
        /// НазваниеПроекта.
        /// </summary>
        // *** Start programmer edit section *** (Проект.НазваниеПроекта CustomAttributes)

        // *** End programmer edit section *** (Проект.НазваниеПроекта CustomAttributes)
        [StrLen(255)]
        public virtual string НазваниеПроекта
        {
            get
            {
                // *** Start programmer edit section *** (Проект.НазваниеПроекта Get start)

                // *** End programmer edit section *** (Проект.НазваниеПроекта Get start)
                string result = this.fНазваниеПроекта;
                // *** Start programmer edit section *** (Проект.НазваниеПроекта Get end)

                // *** End programmer edit section *** (Проект.НазваниеПроекта Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Проект.НазваниеПроекта Set start)

                // *** End programmer edit section *** (Проект.НазваниеПроекта Set start)
                this.fНазваниеПроекта = value;
                // *** Start programmer edit section *** (Проект.НазваниеПроекта Set end)

                // *** End programmer edit section *** (Проект.НазваниеПроекта Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПроектE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПроектE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПроектE", typeof(IIS.Актуализация_Задач.Проект));
                }
            }
            
            /// <summary>
            /// "ПроектL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПроектL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПроектL", typeof(IIS.Актуализация_Задач.Проект));
                }
            }
        }
    }
}
