//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Актуализация_Задач
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Статус задачи.
    /// </summary>
    // *** Start programmer edit section *** (СтатусЗадачи CustomAttributes)

    // *** End programmer edit section *** (СтатусЗадачи CustomAttributes)
    public enum СтатусЗадачи
    {
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (СтатусЗадачи.Выполнено CustomAttributes)

        // *** End programmer edit section *** (СтатусЗадачи.Выполнено CustomAttributes)
        Выполнено,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (СтатусЗадачи.Проверка CustomAttributes)

        // *** End programmer edit section *** (СтатусЗадачи.Проверка CustomAttributes)
        Проверка,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (СтатусЗадачи.ВПроцессеОбсуждения CustomAttributes)

        // *** End programmer edit section *** (СтатусЗадачи.ВПроцессеОбсуждения CustomAttributes)
        ВПроцессеОбсуждения,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (СтатусЗадачи.ЖдутУточнения CustomAttributes)

        // *** End programmer edit section *** (СтатусЗадачи.ЖдутУточнения CustomAttributes)
        ЖдутУточнения,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (СтатусЗадачи.Отложено CustomAttributes)

        // *** End programmer edit section *** (СтатусЗадачи.Отложено CustomAttributes)
        Отложено,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (СтатусЗадачи.Форум CustomAttributes)

        // *** End programmer edit section *** (СтатусЗадачи.Форум CustomAttributes)
        Форум,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (СтатусЗадачи.ВнешнийФорум CustomAttributes)

        // *** End programmer edit section *** (СтатусЗадачи.ВнешнийФорум CustomAttributes)
        ВнешнийФорум,
    }
}
