/*flexberryautogenerated="false"*/
namespace IIS.Актуализация_Задач
{
    using System;
    using ICSSoft.STORMNET.Web.Controls;
    using ICSSoft.STORMNET.FunctionalLanguage;
    using ICSSoft.STORMNET.Windows.Forms;
    using ICSSoft.STORMNET;

    using Resources;

    public partial class ЗадачаРазвитияL : BaseListForm<Задача>
    {
        /// <summary>
        /// Конструктор без параметров,
        /// инициализирует свойства, соответствующие конкретной форме.
        /// </summary>
        public ЗадачаРазвитияL() : base(Задача.Views.ЗадачаРазвитияL)
        {
            EditPage = ЗадачаE.FormPath;
        }
                
        /// <summary>
        /// Путь до формы.
        /// </summary>
        public static string FormPath
        {
            get { return "~/forms/Zadacha/ZadachaRazvitiyaL.aspx"; }
        }

        /// <summary>
        /// Вызывается самым первым в Page_Load.
        /// </summary>
        protected override void Preload()
        {
          ExternalLangDef langdef = ExternalLangDef.LanguageDef;

          WebObjectListView1.LimitFunction = langdef.GetFunction(langdef.funcEQ,
          new VariableDef(langdef.BoolType, Information.ExtractPropertyName<Задача>(x => x.Поддержка)), false);
        }

        /// <summary>
        /// Вызывается самым последним в Page_Load.
        /// </summary>
        protected override void Postload()
        {
        }
    }
}
