/*flexberryautogenerated="false"*/
namespace IIS.Актуализация_Задач
{
    using System;
    using ICSSoft.STORMNET.Web.Controls;
    using ICSSoft.STORMNET.FunctionalLanguage;
    using ICSSoft.STORMNET.Windows.Forms;
    using ICSSoft.STORMNET;

    using Resources;

    public partial class ЗадачаПоддержкиL : BaseListForm<Задача>
    {
        /// <summary>
        /// Конструктор без параметров,
        /// инициализирует свойства, соответствующие конкретной форме.
        /// </summary>
        public ЗадачаПоддержкиL() : base(Задача.Views.ЗадачаПоддержкиL)
        {
            EditPage = ЗадачаE.FormPath;
        }
                
        /// <summary>
        /// Путь до формы.
        /// </summary>
        public static string FormPath
        {
            get { return "~/forms/Zadacha/ZadachaPodderzhkiL.aspx"; }
        }

        /// <summary>
        /// Вызывается самым первым в Page_Load.
        /// </summary>
        protected override void Preload()
        {           
           ExternalLangDef langdef = ExternalLangDef.LanguageDef;

           WebObjectListView1.LimitFunction = langdef.GetFunction(langdef.funcEQ,
           new VariableDef(langdef.BoolType, Information.ExtractPropertyName<Задача>(x => x.Поддержка)), true);

           string a = Request.QueryString["status"];
          
            switch (a)
           {
               case "done":
                   WebObjectListView1.LimitFunction = langdef.GetFunction(langdef.funcAND,
                langdef.GetFunction(
        langdef.funcEQ, new VariableDef(langdef.StringType, Information.ExtractPropertyName<Задача>(x => x.Статус)), EnumCaption.GetCaptionFor(СтатусЗадачи.Выполнено)),
                langdef.GetFunction(
                langdef.funcEQ, new VariableDef(langdef.BoolType, Information.ExtractPropertyName<Задача>(x => x.Поддержка)), true));
                   break;

               case "test":
                   WebObjectListView1.LimitFunction = langdef.GetFunction(langdef.funcAND,
                langdef.GetFunction(
        langdef.funcEQ, new VariableDef(langdef.StringType, Information.ExtractPropertyName<Задача>(x => x.Статус)), EnumCaption.GetCaptionFor(СтатусЗадачи.Проверка)),
                langdef.GetFunction(
                langdef.funcEQ, new VariableDef(langdef.BoolType, Information.ExtractPropertyName<Задача>(x => x.Поддержка)), true));
                   break;

               case "process":
                   WebObjectListView1.LimitFunction = langdef.GetFunction(langdef.funcAND,
                langdef.GetFunction(
        langdef.funcEQ, new VariableDef(langdef.StringType, Information.ExtractPropertyName<Задача>(x => x.Статус)), EnumCaption.GetCaptionFor(СтатусЗадачи.ВПроцессеОбсуждения)),
                langdef.GetFunction(
                langdef.funcEQ, new VariableDef(langdef.BoolType, Information.ExtractPropertyName<Задача>(x => x.Поддержка)), true));
                   break;

               case "wait":
                   WebObjectListView1.LimitFunction = langdef.GetFunction(langdef.funcAND,
                langdef.GetFunction(
        langdef.funcEQ, new VariableDef(langdef.StringType, Information.ExtractPropertyName<Задача>(x => x.Статус)), EnumCaption.GetCaptionFor(СтатусЗадачи.ЖдутУточнения)),
                langdef.GetFunction(
                langdef.funcEQ, new VariableDef(langdef.BoolType, Information.ExtractPropertyName<Задача>(x => x.Поддержка)), true));
                   break;

               case "otl":
                   WebObjectListView1.LimitFunction = langdef.GetFunction(langdef.funcAND,
                langdef.GetFunction(
        langdef.funcEQ, new VariableDef(langdef.StringType, Information.ExtractPropertyName<Задача>(x => x.Статус)), EnumCaption.GetCaptionFor(СтатусЗадачи.Отложено)),
                langdef.GetFunction(
                langdef.funcEQ, new VariableDef(langdef.BoolType, Information.ExtractPropertyName<Задача>(x => x.Поддержка)), true));
                   break;

               case "forum":
                   WebObjectListView1.LimitFunction = langdef.GetFunction(langdef.funcAND,
                langdef.GetFunction(
        langdef.funcEQ, new VariableDef(langdef.StringType, Information.ExtractPropertyName<Задача>(x => x.Статус)), EnumCaption.GetCaptionFor(СтатусЗадачи.Форум)),
                langdef.GetFunction(
                langdef.funcEQ, new VariableDef(langdef.BoolType, Information.ExtractPropertyName<Задача>(x => x.Поддержка)), true));
                   break;

               case "vforum":
                   WebObjectListView1.LimitFunction = langdef.GetFunction(langdef.funcAND,
                langdef.GetFunction(
        langdef.funcEQ, new VariableDef(langdef.StringType, Information.ExtractPropertyName<Задача>(x => x.Статус)), EnumCaption.GetCaptionFor(СтатусЗадачи.ВнешнийФорум)),
                langdef.GetFunction(
                langdef.funcEQ, new VariableDef(langdef.BoolType, Information.ExtractPropertyName<Задача>(x => x.Поддержка)), true));
                   break;
           }
        }

        /// <summary>
        /// Вызывается самым последним в Page_Load.
        /// </summary>
        protected override void Postload()
        {
        }
    }
}
